# Generated by Django 5.0.1 on 2024-01-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev_atributu_id', models.IntegerField()),
                ('hodnota_atributu_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('kod', models.CharField(blank=True, max_length=255, null=True)),
                ('zobrazit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hodnota', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('obrazek_id', models.IntegerField()),
                ('products_ids', models.JSONField()),
                ('attributes_ids', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('obrazek', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cena', models.CharField(max_length=10)),
                ('mena', models.CharField(max_length=3)),
                ('is_published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute', models.IntegerField()),
                ('product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.IntegerField()),
                ('obrazek_id', models.IntegerField()),
                ('nazev', models.CharField(max_length=255)),
            ],
        ),
    ]
