# Generated by Django 5.0.1 on 2024-01-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
