# Generated by Django 5.0.1 on 2024-01-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_eshop', '0002_product_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nazev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='nazev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='zobrazit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
